UIConstants.GARAGE_ACCESSORY_SCROLL_SPEED = 550
UIConstants.ACCESSORY_WIDTH = 100
UIConstants.ACCESSORY_HEIGHT = 100
UIConstants.GARAGE_BOX_SCROLL_SPEED = 550
UIConstants.GARAGE_BOX_WIDTH = 200
UIConstants.GARAGE_BOX_HEIGHT = 200